### ISSUE TITLE
make VESC temperature limitation configurable

### ISSUE THREAD

**Issue by Koxx3** [Koxx3/M365_MC_WB#11]
it's one of the biggest feature on VESC to avoid burning your ESC ;)

**Comment by Netzpfuscher** [comment]
Implemented with
https://github.com/Koxx3/SmartESC_STM32_v2/commit/8c872cf7f953da5473e18d16c02520ccaf5ddcf4

**Comment by Netzpfuscher** [comment]
make temp limit start work with https://github.com/Koxx3/SmartESC_STM32_v2/commit/e175b09dda865c5d760bbc4b101bd71486bf33f1
