### ISSUE TITLE
make VESC auto SHUTDOWN work

### ISSUE THREAD

**Issue by Koxx3** [Koxx3/M365_MC_WB#12]
![image](https://user-images.githubusercontent.com/11454444/146679246-617ba393-e14b-4e80-8c46-a93471a3213d.png)

**Comment by Netzpfuscher** [comment]
implemented with https://github.com/Koxx3/SmartESC_STM32_v2/commit/fe4823eb3ede81a69720b6ae4c0562516acfeda6
