### ISSUE TITLE
Manage the FreeWheel with OFF commutation mosfets

### ISSUE THREAD

**Issue by Foujiwara** [Koxx3/M365_MC_WB#34]
VESC have really free wheel with mosfets OFF when it's in Freewheel (no torque or brake) and when you order torque or brake it start commutation sync with the actual motor speed without "Clonk"

on Acutual V2 firm when we Have fault it stop the mosfet commutation and when it's release it make big Clonk that make peak voltage in power supply and motor blocking for a short time 
Also on Openloop mode, when we stop the openlook we have a big Clonk

**Comment by Netzpfuscher** [comment]
Solved with PWM off feature
