### ISSUE TITLE
make one version without settings Limitation and one with settings Limitation in VESCtool

### ISSUE THREAD

**Issue by Foujiwara** [Koxx3/M365_MC_WB#35]
1 - Making one  version without the limitation popup in the VESCtool when we save the config (that bordering me a bit, the notif is random i dont really understand it's for what, for exemple in Hall sensor, it make me popup for nothing cuz it's not setting link with the power or current or temp etc ...

2 - Create a version that cannot be exceeded from fixed values for the noobs, because when we will have the noobs ppl want to use V2 they will select random value and burn the ESC for sure

VESC have the same, one Firm Unlimited, and one limited we can't exceeded value determined by them

**Comment by Netzpfuscher** [comment]
Closed with new commit. 
limits 1/0 terminal command can disable hardware limits
