### ISSUE TITLE
Case sensitivity mismatch in task_pwr.c causing build failure in Linux

### ISSUE THREAD

**Issue by uski** [Koxx3/M365_MC_WB#46]
Hi

Just checked out the project from GitHub. Ran the docker build script, and it failed because the compiler could not find task_led.h

I searched the repo and there is a task_LED.h

Remember that on Linux, unlike, Windows, filenames are case sensitive.

Modifying :
`#include <task_led.h>`
to
`#include <task_LED.h>`
in `common_files/src/task_pwr.c` fixed the issue.

**Comment by Netzpfuscher** [comment]
Yeah cool haven't found why the automatic build system wasn't running anymore. Now it's fixed 😎

**Comment by Netzpfuscher** [comment]
Closed
