### ISSUE TITLE
Motor setup wizzard & hall sensors

### ISSUE THREAD

**Issue by Koxx3** [Koxx3/M365_MC_WB#6]
After flashing a new controller, Motor sensor wizzard work fine and finish detection, but motor is not spinning with VESCtool control.
I had to do a manual hall sensor detection to get it spinning.

**Comment by Netzpfuscher** [comment]
Fixed with https://github.com/Koxx3/SmartESC_STM32_v2/commit/d672881b0d983bec2eec885999dac8f00b5abc97
