### ISSUE TITLE
Suppot M365 protocol with stock display

### ISSUE THREAD

**Issue by Koxx3** [Koxx3/M365_MC_WB#8]
I would be good to support native protocol for M365 display.

I suggest : 
- VESC protocol enabled by default on BMS UART
- press 10 times the power button to enable/disable to M365 protocol on the display UART.
- disable VESC on BMS UART if not enought CPU time to process both protocols at the same time.

**Comment by Netzpfuscher** [comment]
Throttle and Brake from original dash is maped to ADC1 and ADC2 in Vesc tool. Timeout on dash disconnect is also implemented
